version: '3.1'
services: 
  proxy: 
    image: nginx:mainline-alpine
    restart: always
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/usr/share/www:ro
      - ./log/nginx:/var/log/nginx
    environment: 
      TZ: Asia/Tokyo